Team-Alilm/alilm-be

src/main/kotlin/org/teamalilm/alilmbe/adapter/in/web/controller/BasketSliceController.kt, src/main/kotlin/org/teamalilm/alilmbe/adapter/in/web/controller/MyBasketsController.kt, src/main/kotlin/org/teamalilm/alilmbe/adapter/out/persistence/repository/spring_data/SpringDataBasketRepository.kt, src/main/kotlin/org/teamalilm/alilmbe/application/port/in/use_case/MyBasketsUseCase.kt, src/main/kotlin/org/teamalilm/alilmbe/application/port/out/LoadBasketSlicePort.kt, src/main/kotlin/org/teamalilm/alilmbe/application/service/CrawlingService.kt, src/main/kotlin/org/teamalilm/alilmbe/application/service/MyBasketsService.kt, src/main/kotlin/org/teamalilm/alilmbe/common/config/DataInitializer.kt, src/main/kotlin/org/teamalilm/alilmbe/global/quartz/job/MusinsaSoldoutCheckJob.kt, src/main/kotlin/org/teamalilm/alilmbe/global/security/service/oAuth2/handler/CustomSuccessHandler.kt
나의 상품 조회 API를 만들었어요.
- 스웨거에 해당 API 명세가 있으니 참고 부탁드려요.
나의 상품만들 조회 하는 api를 제공합니다.
=> 10 my baskets

src/main/kotlin/org/teamalilm/alilm/adapter/in/web/controller/baskets/BasketsRegisteredController.kt, src/main/kotlin/org/teamalilm/alilm/common/companion/StringConstant.kt, src/main/kotlin/org/teamalilm/alilm/global/quartz/job/MusinsaSoldoutCheckJob.kt
=> hotfix : 제품 완전 품절 시 품절 키워드 실별해서 2중 체크 로직 추가했어요.

src/main/kotlin/org/teamalilm/alilm/adapter/in/web/advice/RestControllerAdvice.kt, src/main/kotlin/org/teamalilm/alilm/application/service/CrawlingService.kt, src/main/kotlin/org/teamalilm/alilm/common/filter/LoggingFilter.kt
=> 17 로깅 필터에서 헬스체크 api 제거

src/main/kotlin/org/teamalilm/alilm/application/service/CrawlingService.kt
=> feat: 지원하지 않는 url이 온다면 예외를 발생 시킵니다

build.gradle.kts, src/main/kotlin/org/teamalilm/alilm/adapter/out/gateway/FcmSendGateway.kt, src/main/kotlin/org/teamalilm/alilm/adapter/out/persistence/adapter/BasketAdapter.kt, src/main/kotlin/org/teamalilm/alilm/application/port/out/SendAlilmBasketPort.kt, src/main/kotlin/org/teamalilm/alilm/global/quartz/job/MusinsaSoldoutCheckJob.kt, src/test/kotlin/org/teamalilm/alilm/adapter/out/gateway/FcmSendGatewayTest.kt
=> feat: fcm 서비스 개발 완료

.github/workflows/aws.yml
=> fix: "" 추가했어요.

.github/workflows/aws.yml
=> fix: FirebaseSecretKey 설정

src/test/kotlin/org/teamalilm/alilm/adapter/out/gateway/FcmSendGatewayTest.kt
=> feat: test 비활성화

src/main/kotlin/org/teamalilm/alilm/adapter/out/persistence/entity/FcmTokenJpaEntity.kt
=> fix: entity 네이밍 이슈를 제거해요.

src/test/kotlin/org/teamalilm/alilm/adapter/out/gateway/FcmSendGatewayTest.kt
=> fix: fcm token 발송 로직 정비

src/main/kotlin/org/teamalilm/alilm/adapter/out/gateway/FcmSendGateway.kt, src/main/kotlin/org/teamalilm/alilm/adapter/out/persistence/entity/MemberJpaEntity.kt, src/main/kotlin/org/teamalilm/alilm/adapter/out/persistence/entity/ProductJpaEntity.kt, src/main/kotlin/org/teamalilm/alilm/global/jpa/base/BaseEntity.kt, src/main/kotlin/org/teamalilm/alilm/global/jpa/base/BaseTimeEntity.kt, src/main/kotlin/org/teamalilm/alilm/global/quartz/job/MusinsaSoldoutCheckJob.kt, src/main/kotlin/org/teamalilm/alilm/global/security/service/oAuth2/handler/CustomSuccessHandler.kt, src/main/resources/application-local.yml, src/main/resources/application-prod.yml
=> Hotpix 회원 가입

src/main/kotlin/org/teamalilm/alilm/adapter/out/persistence/adapter/BasketAdapter.kt, src/main/kotlin/org/teamalilm/alilm/adapter/out/persistence/entity/MemberJpaEntity.kt, src/main/kotlin/org/teamalilm/alilm/adapter/out/persistence/mapper/ProductMapper.kt, src/main/kotlin/org/teamalilm/alilm/application/port/out/LoadSliceBasketPort.kt, src/main/kotlin/org/teamalilm/alilm/application/service/BasketSliceService.kt
=> feat: 상품 테이블에 기다리는 사람 수가 기록되지 않아요.

src/test/kotlin/org/teamalilm/alilm/adapter/out/gateway/FcmSendGatewayTest.kt
=> feat: 테스트 코드 이슈 주석처리

src/test/kotlin/org/teamalilm/alilm/adapter/out/gateway/FcmSendGatewayTest.kt
=> fix: test code를 제거해요.

src/main/kotlin/org/teamalilm/alilm/adapter/in/web/advice/RestControllerAdvice.kt, src/main/kotlin/org/teamalilm/alilm/common/error/ErrorMessage.kt
=> feat: 상품 409 예외가 반영이 안되어서 hotfix해요.

src/main/kotlin/org/teamalilm/alilm/adapter/out/persistence/entity/FcmTokenJpaEntity.kt, src/main/kotlin/org/teamalilm/alilm/global/quartz/job/MusinsaSoldoutCheckJob.kt
=> feat: 품절 체크하다가 예외가 발생한 것들 슬랙으로 발송하도록

src/main/kotlin/org/teamalilm/alilm/adapter/in/web/advice/RestControllerAdvice.kt, src/main/kotlin/org/teamalilm/alilm/adapter/in/web/controller/member/MyInfoController.kt, src/main/kotlin/org/teamalilm/alilm/adapter/out/persistence/entity/FcmTokenJpaEntity.kt, src/main/kotlin/org/teamalilm/alilm/adapter/out/persistence/repository/BasketRepository.kt, src/main/kotlin/org/teamalilm/alilm/application/port/in/use_case/MyInfoUseCase.kt, src/main/kotlin/org/teamalilm/alilm/application/service/MyInfoService.kt, src/main/kotlin/org/teamalilm/alilm/common/error/ErrorMessage.kt, src/main/kotlin/org/teamalilm/alilm/global/quartz/job/MusinsaSoldoutCheckJob.kt, src/main/kotlin/org/teamalilm/alilm/global/security/service/oAuth2/handler/CustomSuccessHandler.kt
사용자가 이제 자신의 이메일, 닉네임을 조회 할 수 있어요.
=> 49 mypage에 닉네임이랑 이메일 출력하는 api를 만들었어요

src/main/kotlin/org/teamalilm/alilm/adapter/in/web/controller/products/PriceHistoryController.kt, src/main/kotlin/org/teamalilm/alilm/adapter/out/persistence/adapter/PriceAdapter.kt, src/main/kotlin/org/teamalilm/alilm/adapter/out/persistence/entity/PriceJpaEntity.kt, src/main/kotlin/org/teamalilm/alilm/adapter/out/persistence/mapper/PriceMapper.kt, src/main/kotlin/org/teamalilm/alilm/adapter/out/persistence/repository/PriceRepository.kt, src/main/kotlin/org/teamalilm/alilm/adapter/out/persistence/repository/spring_data/SpringDataPriceRepository.kt, src/main/kotlin/org/teamalilm/alilm/application/port/in/use_case/PriceHistoryUseCase.kt, src/main/kotlin/org/teamalilm/alilm/application/port/out/AddPricePort.kt, src/main/kotlin/org/teamalilm/alilm/application/port/out/LoadPricePort.kt, src/main/kotlin/org/teamalilm/alilm/application/service/PriceHistoryService.kt, src/main/kotlin/org/teamalilm/alilm/common/config/SecurityConfig.kt, src/main/kotlin/org/teamalilm/alilm/common/error/ErrorMessage.kt, src/main/kotlin/org/teamalilm/alilm/common/error/NotFoundPriceException.kt, src/main/kotlin/org/teamalilm/alilm/domain/Price.kt, src/main/kotlin/org/teamalilm/alilm/global/quartz/job/MusinsaSoldoutCheckJob.kt, src/main/kotlin/org/teamalilm/alilm/global/util/DateFormatter.kt
cron job에서 가격 히스토리 같이 기록하게 추가했어요!
백엔드 서버를 로컬에서 prod에 붙여서 돌리면 가격 히스토리가 일정 간격보다 더 쌓일 수 있어요.
=> feat: 가격 히스토리를 저장해요

core/src/main/kotlin/application/service/NotificationService.kt
**에이블리 pr 이후 반영 해야합니다.**
알림 발송 이후 alilm table에 저장 해야합니다.
사용자 영향은 없습니다.
=> feat: alilm을 발송하고 alilm table에 저장

api/src/main/kotlin/adapter/in/web/controller/product/ProductCategoryController.kt, core/src/main/kotlin/adapter/out/persistence/adapter/ProductAdapter.kt, core/src/main/kotlin/adapter/out/persistence/repository/ProductRepository.kt, core/src/main/kotlin/application/port/in/use_case/ProductCategoryUseCase.kt, core/src/main/kotlin/application/port/out/LoadProductPort.kt, core/src/main/kotlin/application/service/ProductCategoryService.kt
=> feat: 최근 재입고 상품 반환 api 제작

crawler/src/main/kotlin/application/handler/impl/MusinsaHandler.kt, crawler/src/main/kotlin/application/port/use_case/ProductCrawlingUseCaseResolver.kt, crawler/src/main/kotlin/application/service/CM29ProductCrawlingService.kt, crawler/src/main/kotlin/application/service/MusinsaProductCrawlingService.kt, crawler/src/main/kotlin/application/service/ZigzagProductCrawlingService.kt, crawler/src/main/kotlin/controller/ProductCrawlingController.kt, crawler/src/main/kotlin/error/NotParsingHtml.kt, crawler/src/main/kotlin/gateway/CrawlingGateway.kt, crawler/src/main/kotlin/gateway/impl/HtmlCrawlingGateway.kt, domain/src/main/kotlin/domain/product/Store.kt
=> feat: zigzag crawling service dev

api/src/main/kotlin/adapter/in/web/controller/member/MyAlilmHistoryContoller.kt, api/src/main/kotlin/adapter/in/web/controller/member/MyAlilmReadController.kt, core/src/main/kotlin/adapter/out/persistence/adapter/AlilmAdapter.kt, core/src/main/kotlin/adapter/out/persistence/entity/AlilmJpaEntity.kt, core/src/main/kotlin/adapter/out/persistence/mapper/AlilmMapper.kt, core/src/main/kotlin/adapter/out/persistence/repository/AlilmRepository.kt, core/src/main/kotlin/application/port/in/use_case/MyAlilmHistoryUseCase.kt, core/src/main/kotlin/application/port/in/use_case/MyAlilmReadUseCase.kt, core/src/main/kotlin/application/port/out/LoadAlilmPort.kt, core/src/main/kotlin/application/service/MyAlilmHistoryService.kt, core/src/main/kotlin/application/service/ReadMyAlilmService.kt, core/src/main/kotlin/global/error/ErrorMessage.kt, core/src/main/kotlin/global/error/NotFoundAlilmException.kt, domain/src/main/kotlin/domain/Alilm.kt
- 알림 readYn = true 처리하는 API 추가 개발
- 운영DB에 컬럼 추가 별도로 처리 필요한지 확인해야 합니다.
=> Feat/red dot 알림읽음 처리 API 개발
